// <auto-generated>
//     This code was generated by a tool.
//
//     Project name:    TigerWrapToolkit
//     Source database: TigerWrapDb
//     Timestamp:       2025-07-07 15:24:31
//     Tool name:       TigerWrap
//     Tool database:   TigerWrapDb
//     Tool version:    0.8.7
//     Tool URL:        https://github.com/rkozlowski/TigerWrap
//
//     Changes to this file may cause incorrect behavior 
//     and will be lost if the code is regenerated.
// </auto-generated>

using System.Data;
using System.Data.Common;
using System.Threading;
using Microsoft.Data.SqlClient;
using Microsoft.Data.SqlClient.Server;
using Dapper;

namespace ItTiger.TigerWrap.Core
{
    public partial class ToolkitDbHelper
    {


        // Source table: [Enum].[Casing]
        public enum Casing
        {
            PascalCase = 1,
            CamelCase = 2,
            SnakeCase = 3,
            UnderscoreCamelCase = 4,
            UpperSnakeCase = 5
        }


        // Source table: [Enum].[ClassAccess]
        public enum ClassAccess
        {
            Public = 1,
            Protected = 2,
            Private = 3,
            Internal = 4,
            ProtectedInternal = 5,
            PrivateProtected = 6
        }


        // Source table: [Enum].[NameMatch]
        public enum NameMatch
        {
            ExactMatch = 1,
            Prefix = 2,
            Suffix = 3,
            Like = 4,
            Any = 255
        }


        // Source table: [Enum].[NamePartType]
        public enum NamePartType
        {
            TableNamePreffix = 1,
            TableNameSuffix = 2,
            StoredProcNamePrefix = 3,
            StoredProcNameSuffix = 4,
            TableTypeNamePrefix = 5,
            TableTypeNameSuffix = 6
        }


        // Source table: [Enum].[NameSource]
        public enum NameSource
        {
            TableName = 1,
            StoredProcName = 2,
            TableTypeName = 3
        }


        // Source table: [Enum].[NameType]
        public enum NameType
        {
            Class = 1,
            Method = 2,
            Property = 3,
            Field = 4,
            Parameter = 5,
            LocalVariable = 6,
            TupleField = 7,
            Enum = 8,
            EnumMember = 9
        }


        // Source table: [Enum].[ParamEnumMapping]
        public enum ParamEnumMapping
        {
            ExplicitOnly = 1,
            EnumName = 2,
            EnumNameWithId = 3,
            EnumNameWithOrWithoutId = 4
        }


        // Source table: [Enum].[Status]
        public enum Status
        {
            Active = 1,
            Experimental = 2,
            Deprecated = 3
        }


        // Source table: [Enum].[TemplateType]
        public enum TemplateType
        {
            StartComment = 1,
            End = 2,
            EnumStart = 3,
            EnumEnd = 4,
            EnumEntry = 5,
            ResultTypeStart = 6,
            ResultTypeEnd = 7,
            ResultTypeProperty = 8,
            WrapperStart = 10,
            WrapperEnd = 11,
            WrapperPrep = 12,
            WrapperExec = 13,
            WrapperParam = 14,
            WrapperParamPreExecInput = 15,
            WrapperParamPreExecOutput = 16,
            WrapperExecRs = 17,
            WrapperParamPostExec = 19,
            WrapperStart2 = 20,
            WrapperReturnParam = 21,
            WrapperEnd2 = 22,
            WrapperReturnParamDec = 23,
            TableTypeStart = 24,
            TableTypeEnd = 25,
            TableTypeProperty = 26,
            WrapperParamPreExecTableType = 27,
            TableTypeDtStart = 28,
            TableTypeDtEnd = 29,
            TableTypeDtColumn = 30,
            TableTypeDtRowsStart = 31,
            TableTypeDtRowsEnd = 32,
            TableTypeDtRow = 33,
            TableTypeDtColumnAdd = 34,
            TableTypeDtColumnMaxLen = 35,
            TableTypeDtRowNull = 36,
            StartUsing = 37,
            StartClass = 38,
            StartCommentTool = 39,
            StartCommentEnv = 40,
            StartCommentEnd = 41,
            StaticCtorEnd = 42,
            RsMappingSetup = 43,
            TableTypeDtColumnIdentity = 44,
            TableTypeDtColumnPrecisionScale = 45,
            WrapperExecRsRv = 46,
            EnumStartFlag = 47,
            WrapperEnumStart = 48,
            WrapperEnumEnd = 49,
            WrapperEnumItem = 50,
            StartClassBootstrap = 51
        }


        // Source table: [Enum].[ToolkitResponseCode]
        public enum ToolkitResponseCode
        {
            Ok = 0,
            DbError = 1,
            InternalError = 2,
            UnknownProject = 3,
            InvalidDefaultDatabase = 4,
            InvalidSchema = 11,
            InvalidEnumPattern = 12,
            InvalidProcPattern = 13,
            InvalidClassAccess = 14,
            InvalidLanguage = 15,
            InvalidParamEnumMapping = 16,
            InvalidDatabase = 17,
            UnknownEnum = 18,
            UnknownResultType = 19,
            UnknownTableType = 20,
            UnknownStoredProcedure = 21,
            DuplicateProject = 22,
            NamePatternNotProvided = 23,
            DuplicateEnumMapping = 24,
            DuplicateStoredProcMapping = 25,
            UnexpectedEscChar = 26,
            SchemaNotProvided = 27,
            UnknownStoredProcMapping = 28,
            UnknownEnumMapping = 29,
            InvalidNamePartType = 30,
            UnknownNameNormalization = 31,
            CliUnhandledException = 1000,
            CliFileWriteError = 1001,
            CliInvalidArguments = 1002,
            CliInteractiveNotAllowed = 1003,
            CliMissingConnection = 1004,
            CliMissingProject = 1005,
            CliCodeGenerationFailed = 1006,
            CliMissingParameter = 1007,
            CliNoItemsAvailable = 1008
        }


        // Source table: [Enum].[Language]
        public enum Language
        {
            CSharp = 1
        }


        // Source table: [Enum].[LoggingLevel]
        public enum LoggingLevel
        {
            Error = 1,
            Warning = 2,
            Info = 3,
            Debug = 4,
            Trace = 5
        }


        // Source table: [Enum].[CodePart]
        public enum CodePart
        {
            CodeHeader = 1,
            CodeBootstrap = 2,
            Enums = 3,
            ResultTypes = 4,
            TvpTypes = 5,
            SpWrappers = 6,
            CodeEnd = 7
        }


    }
}
