// <auto-generated>
//     This code was generated by a tool.
//
//     Project name:    TigerWrapToolkit
//     Source database: TigerWrapDb
//     Timestamp:       2025-07-07 15:24:31
//     Tool name:       TigerWrap
//     Tool database:   TigerWrapDb
//     Tool version:    0.8.7
//     Tool URL:        https://github.com/rkozlowski/TigerWrap
//
//     Changes to this file may cause incorrect behavior 
//     and will be lost if the code is regenerated.
// </auto-generated>

using System.Data;
using System.Data.Common;
using System.Threading;
using Microsoft.Data.SqlClient;
using Microsoft.Data.SqlClient.Server;
using Dapper;

namespace ItTiger.TigerWrap.Core
{
    public partial class ToolkitDbHelper
    {


        // Result type for a stored procedure: [Toolkit].[GenerateCode]
        public partial class GenerateCodeResult
        {
            [Column(Name="Id")]
            public int Id { get; set; }
            [Column(Name="CodePartId")]
            public ToolkitDbHelper.CodePart CodePartId { get; set; }
            [Column(Name="Schema")]
            public string Schema { get; set; }
            [Column(Name="Text")]
            public string Text { get; set; }
        }


        // Result type for a stored procedure: [Toolkit].[GetAllProjects]
        public partial class GetAllProjectsResult
        {
            [Column(Name="Id")]
            public short Id { get; set; }
            [Column(Name="Name")]
            public string Name { get; set; }
            [Column(Name="ClassName")]
            public string ClassName { get; set; }
            [Column(Name="NamespaceName")]
            public string NamespaceName { get; set; }
            [Column(Name="LanguageName")]
            public string LanguageName { get; set; }
        }


        // Result type for a stored procedure: [Toolkit].[GetLanguageOptions]
        public partial class GetLanguageOptionsResult
        {
            [Column(Name="Id")]
            public short Id { get; set; }
            [Column(Name="Name")]
            public string Name { get; set; }
            [Column(Name="Value")]
            public long Value { get; set; }
            [Column(Name="IsOverridablePerStoredProc")]
            public bool IsOverridablePerStoredProc { get; set; }
        }


        // Result type for a stored procedure: [Toolkit].[GetLanguages]
        public partial class GetLanguagesResult
        {
            [Column(Name="Id")]
            public ToolkitDbHelper.Language Id { get; set; }
            [Column(Name="Name")]
            public string Name { get; set; }
            [Column(Name="Code")]
            public string Code { get; set; }
        }


        // Result type for a stored procedure: [Toolkit].[GetProjectDbSchemaEnumCandidates]
        public partial class GetProjectDbSchemaEnumCandidatesResult
        {
            [Column(Name="Name")]
            public string Name { get; set; }
            [Column(Name="NameColumn")]
            public string NameColumn { get; set; }
            [Column(Name="NameColumns")]
            public string NameColumns { get; set; }
        }


        // Result type for a stored procedure: [Toolkit].[GetProjectDbSchemaProcs]
        public partial class GetProjectDbSchemaProcsResult
        {
            [Column(Name="Name")]
            public string Name { get; set; }
        }


        // Result type for a stored procedure: [Toolkit].[GetProjectDbSchemas]
        public partial class GetProjectDbSchemasResult
        {
            [Column(Name="Name")]
            public string Name { get; set; }
        }


        // Result type for a stored procedure: [Toolkit].[GetProjectEnumMappings]
        public partial class GetProjectEnumMappingsResult
        {
            [Column(Name="Id")]
            public int Id { get; set; }
            [Column(Name="Schema")]
            public string Schema { get; set; }
            [Column(Name="NameMatchId")]
            public ToolkitDbHelper.NameMatch NameMatchId { get; set; }
            [Column(Name="NamePattern")]
            public string NamePattern { get; set; }
            [Column(Name="EscChar")]
            public string EscChar { get; set; }
            [Column(Name="IsSetOfFlags")]
            public bool IsSetOfFlags { get; set; }
            [Column(Name="NameColumn")]
            public string NameColumn { get; set; }
        }


        // Result type for a stored procedure: [Toolkit].[GetProjectNameNormalizations]
        public partial class GetProjectNameNormalizationsResult
        {
            [Column(Name="Id")]
            public int Id { get; set; }
            [Column(Name="NamePart")]
            public string NamePart { get; set; }
            [Column(Name="NamePartTypeId")]
            public ToolkitDbHelper.NamePartType NamePartTypeId { get; set; }
        }


        // Result type for a stored procedure: [Toolkit].[GetProjects]
        public partial class GetProjectsResult
        {
            [Column(Name="Id")]
            public short Id { get; set; }
            [Column(Name="Name")]
            public string Name { get; set; }
            [Column(Name="ClassName")]
            public string ClassName { get; set; }
            [Column(Name="NamespaceName")]
            public string NamespaceName { get; set; }
            [Column(Name="LanguageName")]
            public string LanguageName { get; set; }
            [Column(Name="LanguageCode")]
            public string LanguageCode { get; set; }
        }


        // Result type for a stored procedure: [Toolkit].[GetProjectStoredProcedureMappings]
        public partial class GetProjectStoredProcedureMappingsResult
        {
            [Column(Name="Id")]
            public int Id { get; set; }
            [Column(Name="Schema")]
            public string Schema { get; set; }
            [Column(Name="NameMatchId")]
            public ToolkitDbHelper.NameMatch NameMatchId { get; set; }
            [Column(Name="NamePattern")]
            public string NamePattern { get; set; }
            [Column(Name="EscChar")]
            public string EscChar { get; set; }
            [Column(Name="LanguageOptionsReset")]
            public long? LanguageOptionsReset { get; set; }
            [Column(Name="LanguageOptionsSet")]
            public long? LanguageOptionsSet { get; set; }
        }


        // Result type for a stored procedure: [Toolkit].[GetResponseCodes]
        public partial class GetResponseCodesResult
        {
            [Column(Name="Id")]
            public ToolkitDbHelper.ToolkitResponseCode Id { get; set; }
            [Column(Name="Name")]
            public string Name { get; set; }
            [Column(Name="Description")]
            public string Description { get; set; }
            [Column(Name="IsSuccess")]
            public bool IsSuccess { get; set; }
        }


    }
}
