// <auto-generated>
//     This code was generated by a tool.
//
//     Project name:    TigerWrapToolkit
//     Source database: TigerWrapDb
//     Timestamp:       2025-07-04 19:02:08
//     Tool name:       TigerWrap
//     Tool database:   TigerWrapDb
//     Tool version:    0.8.7
//     Tool URL:        https://github.com/rkozlowski/TigerWrap
//
//     Changes to this file may cause incorrect behavior 
//     and will be lost if the code is regenerated.
// </auto-generated>

using System.Data;
using System.Data.Common;
using System.Threading;
using Microsoft.Data.SqlClient;
using Microsoft.Data.SqlClient.Server;
using Dapper;

namespace ItTiger.TigerWrap.Core
{
    public partial class ToolkitDbHelper
    {


        // Source table: [Flag].[CodeGenOption]
        [Flags]
        public enum CodeGenOption
        {
            None = 0,
            GenEnums = 1,
            GenResultTypes = 2,
            GenTvpTypes = 4,
            GenSpWrappers = 8,
            GenAll = 32767
        }


    }
}
