// <auto-generated>
//     This code was generated by a tool.
//
//     Project name:    TigerWrapToolkit
//     Source database: TigerWrapDb
//     Timestamp:       2026-07-12 23:43:04
//     Tool name:       TigerWrap
//     Tool database:   TigerWrapDb
//     Tool version:    0.9.1
//     Tool URL:        https://github.com/rkozlowski/TigerWrap
//
//     Changes to this file may cause incorrect behavior 
//     and will be lost if the code is regenerated.
// </auto-generated>

using System.Data;
using System.Data.Common;
using System.Threading;
using Microsoft.Data.SqlClient;
using Microsoft.Data.SqlClient.Server;
using Dapper;
using System.ComponentModel;

namespace ItTiger.TigerWrap.Core
{
    public partial class ToolkitDbHelper
    {


        // Source table: [Enum].[Casing]
        public enum Casing
        {
            PascalCase = 1,
            CamelCase = 2,
            SnakeCase = 3,
            UnderscoreCamelCase = 4,
            UpperSnakeCase = 5
        }


        // Source table: [Enum].[ClassAccess]
        public enum ClassAccess
        {
            Public = 1,
            Protected = 2,
            Private = 3,
            Internal = 4,
            ProtectedInternal = 5,
            PrivateProtected = 6
        }


        // Source table: [Enum].[NameMatch]
        public enum NameMatch
        {
            ExactMatch = 1,
            Prefix = 2,
            Suffix = 3,
            Like = 4,
            Any = 255
        }


        // Source table: [Enum].[NamePartType]
        public enum NamePartType
        {
            TableNamePreffix = 1,
            TableNameSuffix = 2,
            StoredProcNamePrefix = 3,
            StoredProcNameSuffix = 4,
            TableTypeNamePrefix = 5,
            TableTypeNameSuffix = 6
        }


        // Source table: [Enum].[NameSource]
        public enum NameSource
        {
            TableName = 1,
            StoredProcName = 2,
            TableTypeName = 3
        }


        // Source table: [Enum].[NameType]
        public enum NameType
        {
            Class = 1,
            Method = 2,
            Property = 3,
            Field = 4,
            Parameter = 5,
            LocalVariable = 6,
            TupleField = 7,
            Enum = 8,
            EnumMember = 9
        }


        // Source table: [Enum].[ParamEnumMapping]
        public enum ParamEnumMapping
        {
            ExplicitOnly = 1,
            EnumName = 2,
            EnumNameWithId = 3,
            EnumNameWithOrWithoutId = 4
        }


        // Source table: [Enum].[Status]
        public enum Status
        {
            Active = 1,
            Experimental = 2,
            Deprecated = 3
        }


        // Source table: [Enum].[TemplateType]
        public enum TemplateType
        {
            StartComment = 1,
            End = 2,
            EnumStart = 3,
            EnumEnd = 4,
            EnumEntry = 5,
            ResultTypeStart = 6,
            ResultTypeEnd = 7,
            ResultTypeProperty = 8,
            WrapperStart = 10,
            WrapperEnd = 11,
            WrapperPrep = 12,
            WrapperExec = 13,
            WrapperParam = 14,
            WrapperParamPreExecInput = 15,
            WrapperParamPreExecOutput = 16,
            WrapperExecRs = 17,
            WrapperParamPostExec = 19,
            WrapperStart2 = 20,
            WrapperReturnParam = 21,
            WrapperEnd2 = 22,
            WrapperReturnParamDec = 23,
            TableTypeStart = 24,
            TableTypeEnd = 25,
            TableTypeProperty = 26,
            WrapperParamPreExecTableType = 27,
            TableTypeDtStart = 28,
            TableTypeDtEnd = 29,
            TableTypeDtColumn = 30,
            TableTypeDtRowsStart = 31,
            TableTypeDtRowsEnd = 32,
            TableTypeDtRow = 33,
            TableTypeDtColumnAdd = 34,
            TableTypeDtColumnMaxLen = 35,
            TableTypeDtRowNull = 36,
            StartUsing = 37,
            StartClass = 38,
            StartCommentTool = 39,
            StartCommentEnv = 40,
            StartCommentEnd = 41,
            StaticCtorEnd = 42,
            RsMappingSetup = 43,
            TableTypeDtColumnIdentity = 44,
            TableTypeDtColumnPrecisionScale = 45,
            WrapperExecRsRv = 46,
            EnumStartFlag = 47,
            WrapperEnumStart = 48,
            WrapperEnumEnd = 49,
            WrapperEnumItem = 50,
            StartClassBootstrap = 51,
            EnumDescAttribute = 52,
            EnumEntryDescAttribute = 53,
            ExtraUsing = 54
        }


        // Source table: [Enum].[ToolkitResponseCode]
        [Description("Toolkit Response Code")]
        public enum ToolkitResponseCode
        {
            [Description("Operation completed successfully.")]
            Ok = 0,
            [Description("An unexpected database error occured.")]
            DbError = 1,
            [Description("An unexpected internal error occurred.")]
            InternalError = 2,
            [Description("The specified project does not exist.")]
            UnknownProject = 3,
            [Description("The provided default database is not valid or accessible.")]
            InvalidDefaultDatabase = 4,
            [Description("The provided schema is not valid or accessible.")]
            InvalidSchema = 11,
            [Description("Invalid enum name match pattern.")]
            InvalidEnumPattern = 12,
            [Description("Invalid stored procedure name match pattern.")]
            InvalidProcPattern = 13,
            [Description("Invalid class access.")]
            InvalidClassAccess = 14,
            [Description("Invalid programming language.")]
            InvalidLanguage = 15,
            [Description("Invalid enum mapping for parameters.")]
            InvalidParamEnumMapping = 16,
            [Description("The provided database is not valid or accessible.")]
            InvalidDatabase = 17,
            [Description("Unknown enum")]
            UnknownEnum = 18,
            [Description("Unknown result type")]
            UnknownResultType = 19,
            [Description("Unknown table type")]
            UnknownTableType = 20,
            [Description("Unknown stored procedure")]
            UnknownStoredProcedure = 21,
            [Description("Project with provided name already exists")]
            DuplicateProject = 22,
            [Description("Name pattern must be provided")]
            NamePatternNotProvided = 23,
            [Description("Project enum mapping already exists")]
            DuplicateEnumMapping = 24,
            [Description("Project stored procedures mapping already exists")]
            DuplicateStoredProcMapping = 25,
            [Description("Unexpected escape character")]
            UnexpectedEscChar = 26,
            [Description("Name pattern must be provided")]
            SchemaNotProvided = 27,
            [Description("Stored procedure mapping not found")]
            UnknownStoredProcMapping = 28,
            [Description("Enum mapping not found")]
            UnknownEnumMapping = 29,
            [Description("Invalid name part type.")]
            InvalidNamePartType = 30,
            [Description("The specified name normalization entry does not exist for this project.")]
            UnknownNameNormalization = 31,
            [Description("Unexpected application error")]
            CliUnhandledException = 1000,
            [Description("Failed to write to output file")]
            CliFileWriteError = 1001,
            [Description("Invalid command-line arguments")]
            CliInvalidArguments = 1002,
            [Description("Prompt attempted in non-interactive mode")]
            CliInteractiveNotAllowed = 1003,
            [Description("Named connection not found")]
            CliMissingConnection = 1004,
            [Description("Project not found")]
            CliMissingProject = 1005,
            [Description("Code generation failed")]
            CliCodeGenerationFailed = 1006,
            [Description("Missing command parameter")]
            CliMissingParameter = 1007,
            [Description("No selectable items available in CLI prompt")]
            CliNoItemsAvailable = 1008,
            [Description("Generic fail")]
            TigerCliGenericFail = 2002,
            [Description("Invalid arguments")]
            TigerCliInvalidArguments = 2003,
            [Description("Missing required argument")]
            TigerCliMissingRequiredArgument = 2004,
            [Description("Validation error")]
            TigerCliValidationError = 2005,
            [Description("Interactive not allowed")]
            TigerCliInteractiveNotAllowed = 2006,
            [Description("No command")]
            TigerCliNoCommand = 2007,
            [Description("Unhandled exception")]
            TigerCliUnhandledException = 2008,
            [Description("Cancelled")]
            TigerCliCancelled = 2009
        }


        // Source table: [Enum].[Language]
        public enum Language
        {
            CSharp = 1
        }


        // Source table: [Enum].[LoggingLevel]
        public enum LoggingLevel
        {
            Error = 1,
            Warning = 2,
            Info = 3,
            Debug = 4,
            Trace = 5
        }


        // Source table: [Enum].[CodePart]
        public enum CodePart
        {
            CodeHeader = 1,
            CodeBootstrap = 2,
            Enums = 3,
            ResultTypes = 4,
            TvpTypes = 5,
            SpWrappers = 6,
            CodeEnd = 7
        }


    }
}
