# =============================================
# BuildInstaller.ps1 — TigerWrap Installer Builder
# Author: IT Tiger
# =============================================

$ErrorActionPreference = "Stop"

# Paths
$projectRoot       = Resolve-Path ".."
$cliProject        = "$projectRoot\ItTiger.TigerWrap.Cli\ItTiger.TigerWrap.Cli.csproj"
$versionFile       = "$projectRoot\Version.props"
$issFile           = "$PSScriptRoot\Installer.iss"
$workingDir        = "$PSScriptRoot\WorkingDir"
$cliOutputDir      = "$workingDir\cli"
$sqlOutputDir      = "$workingDir\sql"
$deploymentScripts = "$projectRoot\TigerWrapDb\DeploymentScripts"
$schemaVersionFile = "$projectRoot\TigerWrapDb\Scripts\Script.Version.sql"

# Step 1: Read version from Version.props
[xml]$xml = Get-Content $versionFile
$version = $xml.Project.PropertyGroup.Version
$versionInfo = "$version.0"  # Inno Setup wants 4-part version

# Step 1b: Read the TigerWrapDb schema version from its own source of truth.
# It is deliberately independent of the CLI/product version: the metadata database is versioned by
# Script.Version.sql (which ExpectedDbInfo.CurrentSchemaVersion tracks), and the two move on their
# own schedules. Packaging the full deploy by product version would silently ship - or demand - a
# released artifact belonging to a different schema version.
$schemaVersionMatch = [regex]::Match(
    (Get-Content $schemaVersionFile -Raw),
    "@version\s+VARCHAR\(50\)\s*=\s*'(?<v>[^']+)'")
if (-not $schemaVersionMatch.Success) {
    throw "Could not read the TigerWrapDb schema version from $schemaVersionFile."
}
$schemaVersion = $schemaVersionMatch.Groups['v'].Value

Write-Host "`nBuilding TigerWrap Installer v$version (TigerWrapDb $schemaVersion)..." -ForegroundColor Cyan

# Step 2: Clean working directory
Write-Host "Cleaning WorkingDir..."
Remove-Item "$workingDir\*" -Recurse -Force -ErrorAction SilentlyContinue

# Step 3: Publish CLI
Write-Host "Publishing CLI to $cliOutputDir..."
dotnet publish $cliProject -c Release -o $cliOutputDir

# Step 3b: Derive the required .NET runtime from the published runtime config
$runtimeConfigFile = "$cliOutputDir\tiger-wrap.runtimeconfig.json"
$runtimeOptions = (Get-Content $runtimeConfigFile -Raw | ConvertFrom-Json).runtimeOptions
$frameworks = @($runtimeOptions.framework) + @($runtimeOptions.frameworks) | Where-Object { $_ }
if (@($frameworks).Count -ne 1 -or $frameworks[0].name -ne 'Microsoft.NETCore.App') {
    $found = ($frameworks | ForEach-Object { "$($_.name) $($_.version)" }) -join ', '
    throw "Expected a single Microsoft.NETCore.App framework reference in $runtimeConfigFile; found: $found. The installer prerequisite check only handles the base .NET runtime."
}
$runtimeName       = $frameworks[0].name
$runtimeVersion    = $frameworks[0].version
$runtimeMajorMinor = ($runtimeVersion -split '\.')[0..1] -join '.'
Write-Host "Required runtime: $runtimeName $runtimeVersion (x64)"

# Step 3c: Generate the Inno Setup defines consumed by Installer.iss / dotnet.iss
$dotnetDefines = @"
; Auto-generated by BuildInstaller.ps1 from tiger-wrap.runtimeconfig.json - do not edit.
#define DotNetFrameworkName "$runtimeName"
#define DotNetRuntimeVersion "$runtimeVersion"
#define DotNetRuntimeMajorMinor "$runtimeMajorMinor"
"@
Set-Content -Path "$workingDir\DotNetRuntime.iss" -Value $dotnetDefines

# Step 4: Copy SQL scripts
Write-Host "Copying SQL scripts..."
New-Item -ItemType Directory -Path $sqlOutputDir -Force | Out-Null

# Copy all upgrade scripts
Get-ChildItem "$deploymentScripts\TigerWrapDb_Upgrade_*.sql" |
    Copy-Item -Destination $sqlOutputDir

# Copy the full deploy script for the current TigerWrapDb schema version.
# 'tiger-wrap db install' resolves exactly this file from {app}\sql, so a missing artifact is a
# broken installer, not a warning.
$fullDeploy = "$deploymentScripts\TigerWrapDb_FullDeploy_v_$schemaVersion.sql"
if (-not (Test-Path $fullDeploy)) {
    throw "Full deploy script not found: $fullDeploy. 'db install' cannot work without it."
}
Copy-Item $fullDeploy -Destination $sqlOutputDir

# The packaged full deploy must carry the install guard (Script.PreInstallEmptyCheck.sql), which
# is only present when the artifact was generated with the install guard active in the
# pre-deployment script.
if (-not (Select-String -Path $fullDeploy -SimpleMatch -Quiet `
        -Pattern "TigerWrapDb installation refused")) {
    throw "Full deploy script $fullDeploy does not contain the empty-database install guard."
}

# Step 5: Generate VERSION.txt
Write-Host "Generating VERSION.txt..."
Set-Content -Path "$workingDir\VERSION.txt" -Value $version

# Step 6: Update Installer.iss with version info
Write-Host "Updating Installer.iss..."
(Get-Content $issFile) `
    -replace '^; Version:\s*.*$', "; Version:     $version" `
    -replace '^AppVersion=.*$', "AppVersion=$version" `
    -replace '^VersionInfoVersion=.*$', "VersionInfoVersion=$versionInfo" `
    -replace '^OutputBaseFilename=.*$', "OutputBaseFilename=TigerWrapSetup_$($version -replace '\.', '_')" |
    Set-Content $issFile


# Step 7: Locate ISCC.exe from registry
Write-Host "Resolving Inno Setup Compiler (ISCC.exe)..."
$innoKey = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Inno Setup 7_is1"
$innoPath = (Get-ItemProperty -Path $innoKey -ErrorAction SilentlyContinue).InstallLocation

if (-not $innoPath -or !(Test-Path "$innoPath\ISCC.exe")) {
    throw "Inno Setup Compiler (ISCC.exe) not found. Please install Inno Setup 7."
}

$innoSetupExe = Join-Path $innoPath "ISCC.exe"

# Step 8: Compile installer
Write-Host "Compiling installer with ISCC..."
& "$innoSetupExe" "$issFile"
if ($LASTEXITCODE -ne 0) {
    throw "ISCC failed with exit code $LASTEXITCODE."
}

Write-Host "`nTigerWrap installer built successfully." -ForegroundColor Green

